### ISSUE TITLE
1 out of 3 pod is able to connect rabbitMQ

### ISSUE THREAD

**Issue by vrathore18** [bitnami/bitnami-docker-rabbitmq#103]
I have 3 pods when all 3 pods tries to connect to rabbitmq simultaneously then only one is able to connect to RabbitMQ, other 2 are in hang state. When I recreate them 1 at a time then all 3 connects. 

Is there any fix for this issue?

**Comment by juan131** [comment]
HI @vrathore18 

Could you please provide the steps to reproduce the scenario (commands to install the RabbitMQ chart you used and how you created the clients)? Thanks in advance
