### ISSUE TITLE
Respect cgroup memory limits

### ISSUE THREAD

**Issue by mltsy** [bitnami/bitnami-docker-rabbitmq#104]
When running in a container with resource limits, the official rabbitmq docker image checks the cgroup memory limits to automatically generate a config with the correct memory total: https://github.com/docker-library/rabbitmq/blob/master/3.8/alpine/docker-entrypoint.sh#L296

This image doesn't seem to do that.  When I launch it with a memory limit into my kubernetes cluster, the Rabbit UI shows the high watermark as 40% of the total memory on the node.  It would be great to use a similar tactic in this image to automatically set the `total_memory_available_override_value` equal to the cgroup's memory limit so that this information doesn't have to be redundantly specified in the rabbit config (`extraConfiguration: total_memory_available_override_value`) and the container config (`resources.limits.memory`).

**Comment by javsalgar** [comment]
Hi,

That seems very interesting, we'll take a look into that. Thank you very much for the feeback. I will create an internal task for evaluation and we will update the ticket as soon as we have more news about it.

**Comment by CezarManea** [comment]
Hi,

Any updates on this issue?

**Comment by juan131** [comment]
Hi @CezarManea @mltsy 

This was implemented very recently. Please take a look to link below that describes how to configure the watermark limits:

- https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#memory-high-watermark

Please do not hesitate to let us know if you have any questions about this.

**Comment by CezarManea** [comment]
Thank you! I was actually using the docker image without the helm chart.
A simple solution I found was to mount **advanced.config** file to override the **total_memory_available_override_value**

**Comment by mltsy** [comment]
This is great!  Thanks for the notification!  I'll be setting up a new instance soon, and will test it out then.
