### ISSUE TITLE
Enable Self-Signed SSL Certificate Generation

### ISSUE THREAD

**Issue by nitrag** [bitnami/bitnami-docker-rabbitmq#106]
We have this rabbitmq image deployed to AWS EKS Kubernetes. We do not want to expose the management interface to the web, so this would require an internal load balancer. We don't want to pay for an internal Application Load Balancer (ALB) when we are already paying for a Network Load Balancer (NLB). We currently have our internal NLB setup to forward ports 5672 and 15672. However, Chrome likes to force HTTPS and since rabbitmq management interface isn't listening for HTTPS chrome errors with `SSL Protocol Error` and you have to clear HSTS and browser cache in order for Chrome to forget the url was HTTPS so you can then access the management interface again over HTTP. This is tedious and confusing to new users.

I am requesting auto-generation of a self-signed SSL certificate which could be configured with a single environment variable ``RABBITMQ_SSL_HOSTNAME`. 

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout rabbitmq-ssl.key -out rabbitmq-ssl.crt -subj "/CN=${RABBITMQ_SSL_HOSTNAME}/O=${RABBITMQ_SSL_HOSTNAME}"
```

and to add it to the config file: https://www.rabbitmq.com/management.html#single-listener-https

**Comment by andresbono** [comment]
Hi @nitrag, what do you think about introducing an intermediate container acting as reverse proxy? You can use Nginx or Apache to do so.

```
         +-----+         +-----------+        +----------+
+------->+ NLB +-------->+ REV PROXY +------->+ RABBITMQ |
  HTTPS  +-----+  HTTPS  +-----------+  HTTP  +----------+

```

**Comment by nitrag** [comment]
I found a better solution.  If you were to add the following line of code, it basically will disable the caching of HTTPS. I have tested this in my cluster and it works. I will create a PR for you.

librabbitmq.sh (line 186):
```
{rabbitmq_management,
    [
      {listener, [{port, $RABBITMQ_MANAGER_PORT_NUMBER}, {ip, "$RABBITMQ_MANAGER_BIND_IP"}]},
      {strict_transport_security, "max-age=0;"}
    ]
  }
```


https://www.rabbitmq.com/management.html

**Comment by andresbono** [comment]
Thanks @nitrag! 🎉 We will review the PR shortly.
