### ISSUE TITLE
some Pods is not able to connect to rabbitMQ service

### ISSUE THREAD

**Issue by vrathore18** [bitnami/bitnami-docker-rabbitmq#107]
I am using 
name: rabbitmq
version: 6.12.1
I deployed rabbitmq on "rabbitmq" namespace.
Now I am passing rabbit connection string to all my pod's configmap
`RABBIT_MQ_CONNECTION: amqp://{{ .Values.external.rabbitMQUser }}:{{ .Values.external.rabbitMQPassword }}@{{ .Values.external.rabbitMQService }}/ `

But when I see the logs, only only pod is able to connect to the rabbitmq. All other are giving 

`"msg":"config.queue.rabbitMQconnection: error Error: connect ECONNREFUSED`

But when I kill the pod and allow it to restart; it connects. happening to all the pods. Seems like RabbitMq is unable to allow connection request simultaneously. Is there any work around/ fix?

I am almost using the default value.yaml file, just enabled the tls:

  tls:
    enabled: false
    failIfNoPeerCert: false
    sslOptionsVerify: verify_none
    caCertificate: "../tls/ca_certificate.pem"
    serverCertificate: "../tls/server_certificate.pem"
    serverKey: "../tls/server_key.pem"
    # existingSecret: name-of-existing-secret-to-rabbitmq

**Comment by dani8art** [comment]
Hello @vrathore18 

Thank you for opening this issue. I will try to reproduce the issue in my environment so I can understand better what is happening. There are two things I would need to know.

- Are you deploying the client pods in the same namespaces? if not, you should take into account [that](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns)?

- My second question should not be causing the problem but just to be sure, you said:

> I am almost using the default value.yaml file, just enabled the TLS:

but you should note that you have sent `enabled: false` so actually you are not enabling TLS. 

> But when I see the logs, only only pod is able to connect to the rabbitmq. All other are giving

Anyway, this sounds weird to me,  is there just only one pod working properly? which application are you trying to connect to `rabbitmq`?

Regards,
Daniel.

**Comment by vrathore18** [comment]
@dani8art : below are the details:
Are you deploying the client pods in the same namespaces? if not, you should take into account that?: No. I am deploying rabbitmq in "rabbitmq" namespace and application on default namespace. I can't put rabbitmq in default namespace because most of the time I delete/restart all the pods in a namespace and dev team wants rabbitmq not to be deleted.

My bad, actually I have enabled the tls in production but dev/qa tsl is disable. So basically I am using default value.yaml.

Ok, so the issue is. suppose I am deploying 3 pods A, B, C. all three deploy at the same time in the eks but I see the logs only A is connected to rabbitMQ, B and C gives connect ECONNREFUSED error. Now I manually deletes the pods B and when it comes back. It automatically connect to rabbitmq. Now I kill C and when C comes backs in, it also connected automatically. 

So I have total 6 pods, some of them is node.js, some is python.

**Comment by dani8art** [comment]
Hi,

> No. I am deploying rabbitmq in "rabbitmq" namespace and application on default namespace. I can't put rabbitmq in default namespace because most of the time I delete/restart all the pods in a namespace and dev team wants rabbitmq not to be deleted.

Then, I guess you are taking into account https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns.

Do you deploy `rabbitmq` at the same time you are deploying your app? Maybe, you should implement a retry operation in your own application and if the first try fails you can retry again. It seems the `rabbitmq` could not be ready for all the pods but just for the last created one. couldn't it be?

Regards.

**Comment by vrathore18** [comment]
@dani8art : Surly, It might be the case. thanks I'll check and confirm.

**Comment by dani8art** [comment]
Ok, let us know and don't hesitate to contact us. Thank you.

**Comment by dani8art** [comment]
Hi @vrathore18,  did you check it?

**Comment by vrathore18** [comment]
@dani8art : you are absolutely correct. I moved the rabbitmq in a separate namespace. Now the issue is fixed as now the rabbitmq pod is always running. Thanks a alot
