### ISSUE TITLE
/bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted

### ISSUE THREAD

**Issue by cmpmohan** [bitnami/bitnami-docker-rabbitmq#109]
**Description**

We can not run ROOT user privileged container in our environment. so i changed the init container from runAsUser: 0 to runAsuser : 1001 in statefulsets.yaml to achieve the non-root user container. looks like having permission issue while running init container. please have look below error message.

/bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted
 

**Steps to reproduce the issue:**

1. [First Step]
i changed the init container from runAsUser: 0 to runAsuser : 1001 in statefulsets.yaml 
2. [Second Step]
create container now
3. [and so on...]

**Describe the results you received:**

We can not run ROOT user container in our environment. so i changed the init container from runAsUser: 0 to runAsuser : 1001 in statefulsets.yaml to achieve the non-root user container. looks like having permission issue while running init container. please have look below error message.

/bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted

We are looking container has to come up and run as statefulsets model.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

kubernetes version 1.15

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by cmpmohan** [comment]
i have already enabled volumePermissions: enabled :true in values.yaml. 
  
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: stretch
    pullPolicy: Always

still same error "/bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted"

**Comment by cmpmohan** [comment]
i have changed runAsUser : 1001 in initcontainer section. 

 initContainers:
      - name: volume-permissions
        image: "{{ template "rabbitmq.volumePermissions.image" . }}"
        imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
        command: ["/bin/chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "{{ .Values.persistence.path }}"]
        securityContext:
          runAsUser: 1001
        resources:


still same error "/bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted"

**Comment by cmpmohan** [comment]
can some one help us to fix issue?

**Comment by juan131** [comment]
Hi @cmpmohan 

As it's explained in the link below:

- https://github.com/bitnami/charts/tree/master/upstreamed/rabbitmq#adjust-permissions-of-the-persistence-volume-mountpoint

This solution based on using an init container to adjust the permissions should be exclusively used when the K8s distribution you're using **do not support** changing the ownership of the volume using SecurityContext(s). Therefore, if you K8s distro does support it, you should use a **values.yaml** such as the one below:

```yaml
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

volumePermissions:
  enabled: false
```

**Comment by cmpmohan** [comment]
Thanks for yuor response.. i have disabled the volume permission by changing enabled : false..

now pods are up and running..

rabbitmq-0                                    1/1     Running   0          127m
rabbitmq-1                                    1/1     Running   0          126m
rabbitmq-2                                    1/1     Running   0          126m


i could see cluster status  on one of pod  rabbitmq-0 by using below command

================================
I have no name!@rabbitmq-0:/$ rabbitmqctl cluster_status
Cluster status of node rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local ...
Basics

Cluster name: rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local

Disk Nodes

rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local

Running Nodes

rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local

Versions

rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local: RabbitMQ 3.8.2 on Erlang 22.2

Alarms

(none)

Network Partitions

(none)

Listeners

Node: rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local, interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Node: rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local, interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Node: rabbit@rabbitmq-0.rabbitmq-headless.database.svc.cluster.local, interface: [::], port: 15672, protocol: http, purpose: HTTP API

Feature flags

Flag: drop_unroutable_metric, state: enabled
Flag: empty_basic_get_metric, state: enabled
Flag: implicit_default_bindings, state: enabled
Flag: quorum_queue, state: enabled
Flag: virtual_host_metadata, state: enabled
=========================================

i could see same status for all pods in respective pod name. As i'm new to rabbitmq.  my queation is do all pods name should list in rabbitmqctl status? is running as cluster mode or stand alone mode?

**Comment by juan131** [comment]
Hi @cmpmohan 

I was not able to reproduce your issue. I installed the chart with replicas and this is what I obtained:

```console
$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   2/2     Running   0          7m6s
rabbitmq-1   2/2     Running   0          5m53s
rabbitmq-2   2/2     Running   0          4m54s
$ kubectl exec rabbitmq-0 -c rabbitmq rabbitmqctl cluster_status
Cluster status of node rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local ...
Basics

Cluster name: rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local

Disk Nodes

rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local
rabbit@rabbitmq-1.rabbitmq-headless.default.svc.cluster.local
rabbit@rabbitmq-2.rabbitmq-headless.default.svc.cluster.local

Running Nodes

rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local
rabbit@rabbitmq-1.rabbitmq-headless.default.svc.cluster.local
rabbit@rabbitmq-2.rabbitmq-headless.default.svc.cluster.local

Versions

rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local: RabbitMQ 3.8.2 on Erlang 22.2
rabbit@rabbitmq-1.rabbitmq-headless.default.svc.cluster.local: RabbitMQ 3.8.2 on Erlang 22.2
rabbit@rabbitmq-2.rabbitmq-headless.default.svc.cluster.local: RabbitMQ 3.8.2 on Erlang 22.2

Alarms

(none)

Network Partitions

(none)

Listeners

Node: rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Node: rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Node: rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 15672, protocol: http, purpose: HTTP API
Node: rabbit@rabbitmq-1.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Node: rabbit@rabbitmq-1.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Node: rabbit@rabbitmq-1.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 15672, protocol: http, purpose: HTTP API
Node: rabbit@rabbitmq-2.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Node: rabbit@rabbitmq-2.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Node: rabbit@rabbitmq-2.rabbitmq-headless.default.svc.cluster.local, interface: [::], port: 15672, protocol: http, purpose: HTTP API
```

As you can see the information of every node is listed in the "cluster_status" command.

**Comment by wjh-w** [comment]
'/etc/rabbitmq/rabbitmq.conf' -> '/var/lib/rabbitmq/rabbitmq.conf'
chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
chown: changing ownership of '/var/lib/rabbitmq/rabbitmq.conf': Operation not permitted


hello  I would like to ask you how to solve this error reporting authority problem

**Comment by juan131** [comment]
Hi @wjh-w 

Could you please provide more information?
  - How did you come up with the issue? Was it running RabbitMQ using Docker Compose or Helm?
  - Could you share the exact command you used?
  - Where are you running the container (locally, in some K8s environment, etc.)?
Thanks in advance.

**Comment by wjh-w** [comment]
Hi I am in a k8s environment and I don't know how to solve it. Can you help me solve the trouble? I can give you my yaml file



wjh1_2@sina.com
 
From: Juan Ariza Toledano
Date: 2020-11-05 15:00
To: bitnami/bitnami-docker-rabbitmq
CC: wjh-w; Mention
Subject: Re: [bitnami/bitnami-docker-rabbitmq] /bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted (#109)
Hi @wjh-w
Could you please provide more information?
How did you come up with the issue? Was it running RabbitMQ using Docker Compose or Helm?
Could you share the exact command you used?
Where are you running the container (locally, in some K8s environment, etc.)?
Thanks in advance.

**Comment by wjh-w** [comment]
@juan131   I don’t know how to solve this permission problem

**Comment by juan131** [comment]
Hi @wjh-w 

Yes, please! Share the YAML file you're using to deploy RabbitMQ.

Please note that you can use the [Bitnami RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) to deploy RabbitMQ on Kubernetes. This chart already configures RabbitMQ properly adapting the SecurityContext so you shouldn't face permissions issues.

**Comment by wjh-w** [comment]
Hi    The attached is rabbitmq's yaml. Please help me to talk about this problem! ! thank


wjh1_2@sina.com
 
From: Juan Ariza Toledano
Date: 2020-11-05 15:15
To: bitnami/bitnami-docker-rabbitmq
CC: wjh-w; Mention
Subject: Re: [bitnami/bitnami-docker-rabbitmq] /bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted (#109)
Hi @wjh-w
Yes, please! Share the YAML file you're using to deploy RabbitMQ.
Please note that you can use the Bitnami RabbitMQ chart to deploy RabbitMQ on Kubernetes. This chart already configures RabbitMQ properly adapting the SecurityContext so you shouldn't face permissions issues.

**Comment by wjh-w** [comment]
@juan131 HI This is a dynamic storage based on statefulsets.apps. I want to know about adding a parameter to realize the full permissions of the container. I don’t know where to add it.

**Comment by juan131** [comment]
Hi @wjh-w 

Sorry but I didn't get the YAML (you probably sent it via mail but I cannot access it through GitHub).

We implemented two different alternatives for fixing the permissions on RabbitMQ:

1. Using a init container to adapt them:

```yaml
spec:
  template:
    spec:
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/minideb:buster
          command:
            - /bin/bash
          args:
            - -ec
            - |
              mkdir -p "/bitnami/rabbitmq/mnesia"
              chown -R "1001:1001" "/bitnami/rabbitmq/mnesia"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /bitnami/rabbitmq/mnesia
...
```

2. Using a Pod Security Context to adapt the permissions in the container and volumes:

```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
...
```

**Comment by wjh-w** [comment]
hi, I sent the yaml file by email. I will send it to you on github immediately. Please check it out. Thank you.



wjh1_2@sina.com
 
From: Juan Ariza Toledano
Date: 2020-11-06 19:33
To: bitnami/bitnami-docker-rabbitmq
CC: W-jh; Mention
Subject: Re: [bitnami/bitnami-docker-rabbitmq] /bin/chown: changing ownership of '/opt/bitnami/rabbitmq/var/lib/rabbitmq': Operation not permitted (#109)
Hi @wjh-w
Sorry but I didn't get the YAML (you probably sent it via mail but I cannot access it through GitHub).
We implemented two different alternatives for fixing the permissions on RabbitMQ:
Using a init container to adapt them:
spec:
  template:
    spec:
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/minideb:buster
          command:
            - /bin/bash
          args:
            - -ec
            - |
              mkdir -p "/bitnami/rabbitmq/mnesia"
              chown -R "1001:1001" "/bitnami/rabbitmq/mnesia"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /bitnami/rabbitmq/mnesia
...
Using a Pod Security Context to adapt the permissions in the container and volumes:
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
...

**Comment by wjh-w** [comment]
@wjh-w Hi The above is the yaml file of rabbitmq-statefulsets. Please help if you have trouble with permissions.

**Comment by wjh-w** [comment]
The rabbitmq yaml file

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmq-cluster
  labels:
    app: rmq-cluster
spec:
  securityContext:
    runAsUser: 0
  replicas: 3
  selector:
    matchLabels:
      app: rmq-cluster
  serviceName: rmq-cluster
  template:
    metadata:
      labels:
        app: rmq-cluster
    spec:
      serviceAccountName: rmq-cluster
      terminationGracePeriodSeconds: 30
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15672
          name: http
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
        command:
        - sh
        args:
        - -c
        - cp -v /etc/rabbitmq/rabbitmq.conf ${RABBITMQ_CONFIG_FILE}; exec docker-entrypoint.sh
          rabbitmq-server
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: rmq-cluster-secret
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: rmq-cluster-secret
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              key: cookie
              name: rmq-cluster-secret
        - name: K8S_SERVICE_NAME
          value: rmq-cluster
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_NODENAME
          value: rabbit@$(POD_NAME).rmq-cluster.$(POD_NAMESPACE).svc.cluster.local
        - name: RABBITMQ_CONFIG_FILE
          value: /var/lib/rabbitmq/rabbitmq.conf
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 10
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config-volume
          mountPath: /etc/rabbitmq
          readOnly: false
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
          readOnly: false
      volumes:
      - name: config-volume
        configMap:
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
          name: rmq-cluster-config
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage

**Comment by andresbono** [comment]
Hi @wjh-w, it looks like you are using a different container image, [rabbitmq](https://hub.docker.com/_/rabbitmq) instead of the one that we maintain: [bitnami/rabbitmq](https://hub.docker.com/r/bitnami/rabbitmq).

We can only give you support on the latter. As @juan131 mentioned, we highly recommend you to take a look at our [Bitnami RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) if you want to use our container in a Kubernetes environment.

**Comment by wjh-w** [comment]
Can this error be resolved?

**Comment by andresbono** [comment]
Hi @wjh-w, please check my previous comment:

> it looks like you are using a different container image, [rabbitmq](https://hub.docker.com/_/rabbitmq) instead of the one that we maintain: [bitnami/rabbitmq](https://hub.docker.com/r/bitnami/rabbitmq).
> 
> We can only give you support on the latter. As @juan131 mentioned, we highly recommend you to take a look at our [Bitnami RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) if you want to use our container in a Kubernetes environment.

**Comment by wjh-w** [comment]
@andresbono 
 it looks like you are using a different container image, rabbitmq instead of the one that we maintain: bitnami/rabbitmq.

We can only give you support on the latter. As @juan131 mentioned, we highly recommend you to take a look at our Bitnami RabbitMQ chart if you want to use our container in a Kubernetes environment.

**Comment by andresbono** [comment]
@wjh-w, we only only received a quote from my previous comment.
