### ISSUE TITLE
can't login after reset

### ISSUE THREAD

**Issue by scharada** [bitnami/bitnami-docker-rabbitmq#115]
hi, after successfully running an instance, i was able to login using the default credentials. then i needed to reset rabbitmq by issuing 
rabbitmqctl stop_app
rabbitmqctl reset
rabbitmqctl start_app
can login anymore. default credentials do not work anymore.

**Comment by miguelaeh** [comment]
Hi @scharada ,
I would say that is expected, from the RabbitMQ docs: 
```
    Returns a RabbitMQ node to its virgin state.
    Removes the node from any cluster it belongs to, removes all data from the management database, such as configured users and vhosts, and deletes all persistent messages. 
```
https://www.rabbitmq.com/rabbitmqctl.8.html
