### ISSUE TITLE
Support rabbitmq 3.8.4 for bitnami docker images

### ISSUE THREAD

**Issue by chukka** [bitnami/bitnami-docker-rabbitmq#117]
**Description**

rabbitmq 3.8.4 was released  around 10days back , is there any plan to support in bitnami docker images 

https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.4

**Comment by carrodher** [comment]
Hi, we are working on it at this moment so it should be released soon, I can't provide you an exact ETA as there are different factors involved, but It should not be long delayed. Thanks for letting us know

**Comment by vermaabhay** [comment]
waiting for bitnami rabbitmq docker image of version 3.8.4.

**Comment by carrodher** [comment]
Yesterday RabbitMQ 3.8.5 was released in the upstream project. We already released the bitnami rabbitmq image for this new version, [here](https://github.com/bitnami/bitnami-docker-rabbitmq#supported-tags-and-respective-dockerfile-links) you can find the different available tags.

**Comment by chukka** [comment]
Thanks @carrodher , just a follow up question - what is the difference between below tags ?
1. 3.8.5-debian-10-r14 
2. 3.8.5

Do both tags use debian images ? if we want to use it for production what is the recommended tag ?

**Comment by carrodher** [comment]
There are several tags pointing to the same image:
```
3.8-debian-10, 3.8.5-debian-10-r14, 3.8, 3.8.5, latest
```

In the above list there are two types of tags:
- **Rolling tags** (`3.8-debian-10, 3.8, 3.8.5, latest`): Those tags are always pointing to the most recent image. Bitnami publishes a daily tag mainly updating the OS packages, but also it can contain other changes. This tag is released in a daily basis using the `-rXX` suffix and the rest of the tags point to this one, so they are updated on a daily basis.
- **Immutable tags** (`3.8.5-debian-10-r14`): On the other hand, the `-rXX` tag is immutable, this tag with a specific number is released one day and it is not updated anymore.

If you are using containers in a **production** environment, Bitnami recommends using **immutable tags**. This ensures that your deployment is not affected if a new revision inadvertently breaks existing functionality. But you need to be aware of new versions or security patches, you can subscribe to project updates by watching the [bitnami/rabbitmq GitHub repo](https://github.com/bitnami/bitnami-docker-rabbitmq).

You can find more info about rolling tags VS immutable tags in our docs: https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/
