### ISSUE TITLE
warm: command not found when starting from persisted data

### ISSUE THREAD

**Issue by connorearl** [bitnami/bitnami-docker-rabbitmq#119]
**Description**
Container cannot start from persisted data on kubernetes using the helm chart.

**Steps to reproduce the issue:**

1. Start new pod with a pvc setup
2. Delete the pod

**Describe the results you received:**

```
INFO  ==> Persisted data detected. Restoring...
/opt/bitnami/scripts/librabbitmq.sh: line 439: warm: command not found
```

**Describe the results you expected:**

The pod to start and restore successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
19.3.11
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes 1.18.3

**Comment by miguelaeh** [comment]
Hi @connorearl ,
Thank you very much for sharing this bug. It is a typo in that file. This change fixes the problem: https://github.com/bitnami/bitnami-docker-rabbitmq/pull/120
