### ISSUE TITLE
Changing the configuration file format from json to ini broke "RABBITMQ_DISK_FREE_LIMIT"

### ISSUE THREAD

**Issue by gunzl1ng3r** [bitnami/bitnami-docker-rabbitmq#124]
**Description**

When the configuration format for rabbitmq.conf was changed from JSON to INI the setting for "RABBITMQ_DISK_FREE_LIMIT" was broken:

https://github.com/bitnami/bitnami-docker-rabbitmq/commit/d436966984241f95a4c025750180b2ce26d5b92e

As can be seen in line #165 the setting is hardcoded as "disk_free_limit.relative", which is problematic if one wants to use an absolute value. This would require the possibility to set "disk_free_limit.absolute".

Hence, the container won't start if "RABBITMQ_DISK_FREE_LIMIT" is set to "{absolute, 1000000000}".

This was kind of tricky to debug, because (at least) in its default loglevel RabbitMQ does not print an error if there are invalid settings in its configuration.

**Steps to reproduce the issue:**

1. Use `bitnami/rabbitmq:3.8`
1. Set `RABBITMQ_DISK_FREE_LIMIT= "{absolute, 1000000000}"`
1. Try to start the container
1. RabbitMQ won't start
1. Use `bitnami/rabbitmq:3.8.3`
1. Set `RABBITMQ_DISK_FREE_LIMIT= "{absolute, 1000000000}"`
1. Try to start the container
1. RabbitMQ will start

**Describe the results you received:**

See above

**Describe the results you expected:**

RabbitMQ starts and respects my setting :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 23
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-193.6.3.el8_2.x86_64
 Operating System: Red Hat Enterprise Linux 8.2 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 19.6GiB
 Name: wab-dev-cm11
 ID: BHP4:SW2F:AFAM:DJZC:U7BH:4KIX:OC7S:YDFP:XETU:OMAG:7KEK:4KEE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @gunzl1ng3r 

As you mentioned, we moved the configuration file from the "old" Erlang tems to "sysctl" or "ini-like" format, it's documented in the README.md:

- https://github.com/bitnami/bitnami-docker-rabbitmq#383-debian-10-r109

As you said, now you can only set relative limits which is a regression. I just created a PR to address this issue, thanks for reporting it.
