### ISSUE TITLE
Support RABBITMQ_VM_MEMORY_HIGH_WATERMARK?

### ISSUE THREAD

**Issue by Spoon94** [bitnami/bitnami-docker-rabbitmq#130]
I find it doesnot support RABBITMQ_VM_MEMORY_HIGH_WATERMARK option

**Comment by rafariossaa** [comment]
Hi,
  Currently there is not that environment variable. 
  Could you provide more background on the parameters you need to set ?.

**Comment by Spoon94** [comment]
I have a VPS just which ram is only 2G. I want to run kafka_cluser(3 nodes,heap size 256MB),rabbitmq(3 nodes).when i run kafka then run rabbitmq ,the rabbitmq container crashes with reason limited memory

**Comment by rafariossaa** [comment]
Hi,
  Will using custom configuration file work for you? Could you take a look to this [link](https://github.com/bitnami/bitnami-docker-rabbitmq#configuration-file) ?

**Comment by Spoon94** [comment]
Thx

**Comment by rafariossaa** [comment]
You are welcome.
