### ISSUE TITLE
support LDAP lookup for AD

### ISSUE THREAD

**Issue by maxisam** [bitnami/bitnami-docker-rabbitmq#133]
**Description**

Currently it doesn't work with AD

**Additional information you deem important (e.g. issue happens only occasionally):**

suppport more env variable

https://www.rabbitmq.com/ldap.html
https://stackoverflow.com/a/56209575/667767

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. In order to fully understand the issue, please, can you describe a bit more what is your use case, what are you trying to do, and what is the error or limitation you're facing? Thanks!

**Comment by maxisam** [comment]
@carrodher To work with Activity Directory you have to set dn_lookup_bind to do lookup first.

See the link from SO talking about how to make it work with AD.
https://stackoverflow.com/a/56209575/667767

And you can see the settings detail from rabbitmq's document
https://www.rabbitmq.com/ldap.html

**Comment by carrodher** [comment]
The required plugin is enabled when the `RABBITMQ_ENABLE_LDAP` env. variable is set to `true`. In the same way, everything related to LDAP is added to the configuration file, see https://github.com/bitnami/bitnami-docker-rabbitmq#enabling-ldap-support

If there is needed other custom parameters you should be able to use a custom configuration file where you can use all the required values for AD, see https://github.com/bitnami/bitnami-docker-rabbitmq#configuration-file

Are you missing something that needs to be implemented in the image itself?

**Comment by maxisam** [comment]
I suppose I can use the configuration file directly. thx
