### ISSUE TITLE
Configure RabbitMQ for connectivity outside EKS cluster

### ISSUE THREAD

**Issue by SteveL1** [bitnami/bitnami-docker-rabbitmq#135]
Hi,

I am deploying RabbitMQ to an EKS cluster in AWS and everything seems to be deploying successfully but now I need to make both the UI and amqp ports available to services outside the cluster.

I have set the service type to LoadBalancer and the loadBalancerSourceRanges to the correct CIDR range but I still can't connect to. I must be missing something simple but I can't see what.

I'd appreciate any help to get this working!

Thanks

**Comment by marcosbc** [comment]
Hi @SteveL1, in order to properly reproduce this issue, please share the options you used to deploy the chart.

How are you accessing RabbitMQ? Mind the notes when deploying RabbitMQ:

```
Obtain the LoadBalancer IP:

NOTE: It may take a few minutes for the LoadBalancer IP to be available.
      Watch the status with: 'kubectl get svc --namespace default -w myrabbitmq-rabbitmq'

    export SERVICE_IP=$(kubectl get svc --namespace default myrabbitmq-rabbitmq --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")

To Access the RabbitMQ AMQP port:

    echo "URL : amqp://$SERVICE_IP:5672/"

To Access the RabbitMQ Management interface:

    echo "URL : http://$SERVICE_IP:15672/"
```

**Comment by SteveL1** [comment]
Thanks for the reply.

It seems that the network policy was getting in the way :/
