### ISSUE TITLE
Recommendation on updating image 

### ISSUE THREAD

**Issue by SteveL1** [bitnami/bitnami-docker-rabbitmq#136]
Hi,

My pipeline pulls down the lastest image but i'm not sure of the best way to roll this image out.

The default updateStrategy in the values file is OnDelete, if I change this to RollingUpdate then it gets stuck while replacing the last stateful set pod.  

What's the recommended way of updating the image of the pods?

Thanks

**Comment by javsalgar** [comment]
Hi,

Our recommendation is to not use rolling tags (such as `latest`) in your deployments, as you would lose control of the software running in your cluster. If you are having issues updating the images using RollingUpdate, could you let us know from which version you are trying to update and which error appears?

**Comment by SteveL1** [comment]
Hi,

I having change the deployment to pull down a specific version and install security updates.

It seems I was being impatient because it does deploy a new image successfully but it take between 10-15 mins to become healthy.  I'm not sure why it would take this long as there is nothing in the logs after the pvc being attached and the container stays at creating for the whole time.

Steve

**Comment by javsalgar** [comment]
Hi,

In the Kubernetes world, this is something expected (i.e. have some of the containers fail until all the nodes converge to a stable state). Probably it has to do with the fact that the cluster has several nodes. Please let us know if you find any other issue.

**Comment by SteveL1** [comment]
Hi,

That's great, thank you for confirming that.  I'll just have to extend timeouts on monitoring. 👍 

Steve
