### ISSUE TITLE
Provide support for ARM64 Arch docker images

### ISSUE THREAD

**Issue by dbuos** [bitnami/bitnami-docker-rabbitmq#137]
**Description**

Provide support for ARM64 arch in image repository

**Steps to reproduce the issue:**

1. Try to run the image in an ARM64 machine as m6g AWS new instances
2. You'll get an exec format error

**Describe the results you received:**

standard_init_linux.go:211: exec user process caused "exec format error"
When try to run bitnami helm chart for rabbitMq in EKS with m6g arm64 nodes.

**Describe the results you expected:**

When arm64 images where available this should not happen.

**Additional information you deem important (e.g. issue happens only occasionally):**

May be using multiarch build with docker buildx, for example: docker buildx build --platform linux/arm64,linux/amd64 -t bitnami/rabbitmq --push .

**Version**

```
All versions
```

- Output of `docker info`:

```
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:30 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:02:02 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

EKS with nodes m6g.*

**Comment by andresbono** [comment]
Hi @dbuos, we would really work on supporting ARM but unfortunately we are a small team right now and we have a limited bandwidth to work on this. That would require major changes in our pipeline to support building & testing ARM containers.

**Comment by dbuos** [comment]
Hi @andresbono, If there is something that I could do to help in implementing this, and if you could give me some guidance I'll be happy to work on this issue.

**Comment by andresbono** [comment]
Hi, I am sorry but the required changes for supporting the arm architecture in the Bitnami images need to be implemented in different internal tools and systems that are not hosted as part of the public code in the Bitnami GitHub organization.

If you are using the chart, you might want to modify the image values so that it uses another RabbitMQ container with arm support (although not provided by Bitnami). We haven't tested it, but you might want to give it a try.

**Comment by dbuos** [comment]
Thanks for the info, I'll try it that way.
