### ISSUE TITLE
[FEATURE REQUEST] Ability to create additional users

### ISSUE THREAD

**Issue by kjenneycloudhealth** [bitnami/bitnami-docker-rabbitmq#141]
**Description**

Add support for adding additional users via environment variables and/or config file.

**Steps to reproduce the issue:**

NA

**Describe the results you received:**

Launching this image: `docker.io/bitnami/rabbitmq:3.8.9-debian-10-r20` a single user is added via RABBITMQ_USERNAME and RABBITMQ_PASSWORD. There are no options for adding additional users.

**Describe the results you expected:**

I would love to see options for adding additional users.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

```
Docker version 19.03.13, build 4484c46d9d
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 79
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: H4GI:LHX5:TSG6:2ZNK:52ZZ:NDVI:P7NG:GCZU:KG74:MRZM:6OZS:KL3Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 49
  Goroutines: 53
  System Time: 2020-11-05T14:40:22.5956861Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  Thanks for you suggestion.
  I am creating a internal task to add this functionality, however I don't have a ETA for this.
  In any case, PR are welcomed and we will be glad to review and merge it.

**Comment by cosmosgenius** [comment]
we currently handle this by using load_definitions
`custom.conf`
```
management.load_definitions=/opt/bitnami/rabbitmq/etc/rabbitmq/definitions.json
```
`defintions.json`
```
{
    "users":[
        {
            "name":"user1",
            "password":"user1password",
            "tags":""
        },
        {
            "name":"user2",
            "password":"user2password",
            "tags":""
        }
    ],
    "vhosts":[
        {
            "name":"vhost1"
        },
        {
            "name":"vhost2"
        }
    ],
    "permissions":[
        {
            "user":"user1",
            "vhost":"vhost1",
            "configure":".*",
            "write":".*",
            "read":".*"
        },
        {
            "user":"user2",
            "vhost":"vhost2",
            "configure":".*",
            "write":".*",
            "read":".*"
        }
    ]
}
```
both the files are under rabbitmq config dir loaded via volumes
`./etc/rabbitmq:/bitnami/rabbitmq/conf:ro`

**Comment by kjenneycloudhealth** [comment]
If you provision a user with environment variables will using custom.conf overwrite that initially created user or append the users?

**Comment by cosmosgenius** [comment]
3 users for the config i have provided.
But depending on how the definitions are loaded this can be controlled to 2 users or 3 users. I am loading it via management `load_definitions`. If you use the normal `load_definitions` only 2 users would be there.

**Comment by rafariossaa** [comment]
Hi, 
  Sorry for the delay.
  Thanks for the workaround, in any case I will left this task `on-hold` to this functionality to be added by the use of parameters.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
