### ISSUE TITLE
RABBITMQ_LOAD_DEFINITIONS=yes gives error due to merge error

### ISSUE THREAD

**Issue by msvticket** [bitnami/bitnami-docker-rabbitmq#145]
**Description**

I get

/opt/bitnami/scripts/librabbitmq.sh: line 74: The RABBITMQ_LOAD_DEFINITIONS and RABBITMQ_SECURE_PASSWORD environment variables cannot be enabled at once.: command not found

on startup when RABBITMQ_LOAD_DEFINITIONS=yes.

The cause seems to be commit e7404f878f550064a81667c118b820b76de0ee04 which seems to include a merge error.

**Comment by msvticket** [comment]
Well, maybe not an error. Just a weird handling of default values.

**Comment by juan131** [comment]
Hi @msvticket 

> Well, maybe not an error. Just a weird handling of default values.

The default value for `RABBITMQ_LOAD_DEFINITIONS` is `no`, see:

- https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh#L108

While the default value for `RABBITMQ_SECURE_PASSWORD` is `yes`, see:

- https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh#L100

Therefore, by default, there shouldn't be any problem in the initialisation (unless the value for `RABBITMQ_LOAD_DEFINITIONS`)
