### ISSUE TITLE
Request: either document RABBITMQ_USE_LONGNAME or handle it automatically

### ISSUE THREAD

**Issue by philippfreyer** [bitnami/bitnami-docker-rabbitmq#146]
**Description**

I was having issues starting the rabbitmq image due to my node names having dots in them. Apparently the startup scripts do not handle this well, they would then just crash.
I managed to resolve this issue by setting RABBITMQ_USE_LONGNAME=1 in my docker-compose file.

I would suggest that the startup scripts either do that automatically once a dot is detected in the node name or the environment variable is documented in the table of environment variables.

**Steps to reproduce the issue:**

1. Use attached docker-compose file to generate a cluster
[rabbit.docker-compose.txt](https://github.com/bitnami/bitnami-docker-rabbitmq/files/5808970/rabbit.docker-compose.txt)

**Describe the results you received:**

RabbitMQ crashing during startup with incomprehensible error crash dump (only visile with BITNAMI_DEBUG=true set).

**Describe the results you expected:**

Either an understandable error message or a documented setting or the startup script handling this automatically.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Trying on baremetal (Ubuntu) but reproducable on local developer machine (Windows)

**Comment by marcosbc** [comment]
Hi @philippfreyer, note that this is an internal RabbitMQ functionality and is not controlled by environment variables defined by the Bitnami Docker image.

I'm not too confident of using this environment variable automatically, as it could lead to unintended consequences.

However, to make things simpler for users to find this issue, we could also define a new validation [here](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L26) and print something like `When ... it is required to specify RABBITMQ_USE_LONGNAME=1` with the `print_validation_error` function. Feel free to send a PR and contribute the change!

**Comment by philippfreyer** [comment]
Thanks, I will have a look at it and try to come up with a PR once I finished configuring the complete deployment - there may be a few more points that I may want to add...

**Comment by marcosbc** [comment]
Sure! If you find any issues or any points for improvements feel free to send a PR with those changes. We'll be glad to help with the review and release of a new Docker image with those changes.

**Comment by philippfreyer** [comment]
Thanks, found a few issues already with SSL certificate handling, still investigating a few of them, the ones that I understood are already waiting as issues (and one PR), glad to fix those other issues as well via PR, any comments are very appreciated :-)

**Comment by philippfreyer** [comment]
PR ready for review :-)

**Comment by marcosbc** [comment]
Awesome, thanks a lot @philippfreyer! We'll check the PR shortly.

**Comment by philippfreyer** [comment]
Closing the issue since the PR is merged.
