### ISSUE TITLE
Management SSL IP and Port are crossed while assigning

### ISSUE THREAD

**Issue by philippfreyer** [bitnami/bitnami-docker-rabbitmq#148]
**Description**

Noticed this error, when trying to enable SSL  on my RabbitMQ server container:

> 14:15:25.905 [error] Error preparing configuration in phase transform_datatypes:
14:15:25.907 [error]   - Error transforming datatype for: management.ssl.port
14:15:25.907 [error]   - "0.0.0.0" cannot be converted to a(n) integer
14:15:25.908 [error]
14:15:25.908 [error] BOOT FAILED

Checking the code, I found this in https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L229:

```
rabbitmq_print_management_configuration() {
    echo "## Management"
    if rabbitmq_is_ssl_enabled "management_ssl"; then
        echo "management.ssl.port = ${RABBITMQ_MANAGEMENT_BIND_IP}"
        echo "management.ssl.ip = ${RABBITMQ_MANAGEMENT_SSL_PORT_NUMBER}"
        rabbitmq_print_ssl_configuration "management_ssl" "management.ssl"
    else
        # Assume SSL is disabled when no environment variables matching 'RABBITMQ_SSL_*' have been specified
        echo "management.tcp.ip = ${RABBITMQ_MANAGEMENT_BIND_IP}"
        echo "management.tcp.port = ${RABBITMQ_MANAGEMENT_PORT_NUMBER}"
        echo
    fi
}
```

The management IP and Port are assigned in reverse.

**Comment by philippfreyer** [comment]
Created a pull request for you to review that should fix this issue. You are mentioning tests in the PR documentation - any tests that I could run to check the changes? I did not see a test suite...

**Comment by philippfreyer** [comment]
It would be great if the linked PR could get reviewed and hopefully merged soon since this is causing me to add a quite ugly fix to my current deployments :-)

**Comment by miguelaeh** [comment]
Hi @philippfreyer ,
Thank you very much for sharing this issue.
We are going to take care of it.
About the tests, we cannot share them since they are internal but I can tell you we are working to add those SSL tests.
Thankyou very much!

**Comment by philippfreyer** [comment]
Closing the issue since the PR is merged.
