### ISSUE TITLE
RabbitMQ SSL combined certificate cannot be created due to permission denied error 

### ISSUE THREAD

**Issue by philippfreyer** [bitnami/bitnami-docker-rabbitmq#150]
**Description**

I am trying to cluster Bitnami RabbitMQ containers together while communicating using SSL. The containers do not start due to issues with permissions. Setting BITNAMI_DEBUG=true dies sadly not add additional output:

> rabbitmq 14:04:33.31
rabbitmq 14:04:33.31 Welcome to the Bitnami rabbitmq container
rabbitmq 14:04:33.31 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 14:04:33.31 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 14:04:33.31
rabbitmq 14:04:33.32 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 14:04:33.33 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 14:04:33.34 INFO  ==> Initializing RabbitMQ...
rabbitmq 14:04:33.34 DEBUG ==> Creating configuration file...
/opt/bitnami/scripts/librabbitmq.sh: line 413: /etc/rabbitmq_combined_keys.pem: Permission denied

**Steps to reproduce the issue:**

1. [First Step] Use the following docker-compose file, mounting a key and certificate
[docker-compose.txt](https://github.com/bitnami/bitnami-docker-rabbitmq/files/5820933/docker-compose.txt)
2. [Second Step] Startup will fail with the quoted log entry

**Describe the results you received:**

It seems like the folder /etc is only writable to root while the setup process may already be executed as user 1001. I would suggest either moving the config file out of /etc if possible or creating a writable dummy file.

Mounting the file myself with the correct permissions is a workaround for this issue:
```
    volumes:
      - '/db/rabbitmq/primary:/bitnami'
      - '/db/rabbitmq/client/my.host.name:/certs'
      - '/db/rabbitmq/client/my.host.name.combined.cert:/etc/rabbitmq_combined_keys.pem'

```

**Describe the results you expected:**

The combined cert being generated correctly

**Additional information you deem important (e.g. issue happens only occasionally):**

This file seems to be the only one to be generated in `/etc` - the other files seem to be generated in `/opt/bitnami/rabbitmq/etc/rabbitmq/` - is that correct?

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 15
  Running: 5
  Paused: 0
  Stopped: 10
 Images: 50
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.23GiB
 Name: Ubuntu-2004-focal-64-minimal
 ID: VPUU:3W5C:XF7K:V47H:5YF7:THRV:S53W:5RHD:QHL3:V4ZB:UYBR:QGCO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.0, build 980ec85b
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
baremetal

**Comment by dani8art** [comment]
Hi @philippfreyer, yes I was able to reproduce the issue, it seems would be safe to have it at `opt/bitnami/rabbitmq/etc/rabbitmq/` or some other point with the right permission. Would you mind to try a PR? then we can discuss the solution there. It shouldn't be complicated, let's try to modify the library at two point

- https://github.com/bitnami/bitnami-docker-rabbitmq/blob/2fc635cd057a351fc0e3172aaef46dc5d2a0b6e9/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L412
- https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L425-L446

Thanks!

**Comment by philippfreyer** [comment]
Hi @dani8art 
sure, will give you a PR in a few minutes

**Comment by dani8art** [comment]
Thank you so much for this PR @philippfreyer! let's move the conversation there ;)

**Comment by philippfreyer** [comment]
Closing the issue since the PR is merged.
