### ISSUE TITLE
Typo in rabbitmq-env.sh

### ISSUE THREAD

**Issue by alekseev-tn** [bitnami/bitnami-docker-rabbitmq#159]
Hi. 
You have a typo in bitnami-docker-rabbitmq/3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh on the right side of your expression:
export RABBITMQ_COMBINED_CERT_PATH="${RABBITMQ_SSL_KEYFILE:-/tmp/rabbitmq_combined_keys.pem}"
There should be an:
export RABBITMQ_COMBINED_CERT_PATH="${RABBITMQ_COMBINED_CERT_PATH:-/tmp/rabbitmq_combined_keys.pem}"

**Comment by miguelaeh** [comment]
Hi @alekseev-tn ,
Thank you very much for reporting it!
We will take care of it

**Comment by gaby** [comment]
@miguelaeh I submitted a PR to fix this. It seems to be affecting the ability of using TLS

**Comment by miguelaeh** [comment]
Thank you very much!
It seems @javsalgar  is already taking care of it.
