### ISSUE TITLE
Fix Cluster 

### ISSUE THREAD

**Issue by vhuezo** [bitnami/bitnami-docker-rabbitmq#165]
https://github.com/bitnami/bitnami-docker-rabbitmq#step-2-add-a-queue-node-in-your-configuration
I used the Cluster Docker Compose and only that node came out.

![imagen](https://i.imgur.com/WoYe7rh.png)

**Comment by javsalgar** [comment]
Hi,

Could you show your full docker-compose file? Do the logs show anything meaningful?
