### ISSUE TITLE
Please use Erlang 23.3

### ISSUE THREAD

**Issue by michaelklishin** [bitnami/bitnami-docker-rabbitmq#166]
Team RabbitMQ plans on dropping Erlang 22 support as soon as [Erlang 24 goes GA](https://blog.rabbitmq.com/posts/2021/03/erlang-24-support-roadmap/). Please upgrade this image to Erlang 23.3
to avoid any surprises. 23.3 should be supported for roughly another year, till roughly the moment hwen 25.0 ships.

Thank you.

**Comment by Mauraza** [comment]
Hi @michaelklishin,

Thanks for the suggestions, I'm going to create an internal task to check this and upgrade if it's possible. We update the thread when we have more information.

**Comment by Mauraza** [comment]
Hi @michaelklishin,

We just update the version of Erlang 23.3 in the last revision of RabbitMQ. 
You can check it in the Dockerfile. 
https://github.com/bitnami/bitnami-docker-rabbitmq/blob/44676066be647af46bcb7deae068119fe0203433/3.8/debian-10/Dockerfile#L13
