### ISSUE TITLE
Where to define policies?

### ISSUE THREAD

**Issue by nijrajgelani-crest** [bitnami/bitnami-docker-rabbitmq#171]
**Description**

I want to apply a policy that can usually be applied using the following command:

```
rabbitmqctl set_policy HA '^(?!amq\\.).*' '{"ha-mode": "all"}'
```

Is there any way I can define this policy using configuration or provide an initialization script to the container to set up policies?

**Comment by pablogalegoc** [comment]
Hi @nijrajgelani-crest!

You can mount a configuration file like in [bitnami-docker-rabbitmq#configuration-file](https://github.com/bitnami/bitnami-docker-rabbitmq#configuration-file)

**Comment by nijrajgelani-crest** [comment]
Thanks, @pablogalegoc. This might not really be a question suitable for this repo but do you know how I can actually define the policy using the config file?

**Comment by pablogalegoc** [comment]
I'm not an expert on RabbitMQ but it seems policies can't be set on the configuration file (source: [Parameters and Policies](https://www.rabbitmq.com/parameters.html#overview)). Maybe in this case the best way is your second option and adapt the [initialization scripts](https://github.com/bitnami/bitnami-docker-rabbitmq/tree/master/3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq) of the container to best suit your use case 🙂
