### ISSUE TITLE
Missing directories and permissions

### ISSUE THREAD

**Issue by moule3053** [bitnami/bitnami-docker-rabbitmq#179]
**Description**

I'm trying to deploy RabbitMQ in a highly secure Kubernetes cluster that allows running pods only as a non-root user. As a result, I cannot use initContainers to adjust the permission on the mounted volumes. So, when I run the pod I get the error:

`cp: cannot create regular file '/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf': Permission denied`

**Steps to reproduce the issue:**

1. `helm install rabbitmq bitnami/rabbitmq`
2. `kbectl logs rabbitmq-0 -f`

**Describe the results you received:**

I get error

```
rabbitmq 14:40:49.69 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 14:40:49.70 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 14:40:49.75 INFO  ==> Initializing RabbitMQ...
cp: cannot create regular file '/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf': Permission denied
```

**Describe the results you expected:**

RabbitMQ start without problems ...

**Additional information you deem important (e.g. issue happens only occasionally):**

In the case where the permission of the mounted volumes cannot be adjusted using initContainers, the necessary directories need to be created and their ownership changed inside the Dockerfile, like so

```
RUN mkdir -p /opt/bitnami/rabbitmq/.rabbitmq/
RUN mkdir -p /opt/bitnami/rabbitmq/var/lib/rabbitmq/
RUN mkdir -p /opt/bitnami/rabbitmq/var/log/rabbitmq/
RUN mkdir -p /opt/bitnami/rabbitmq/etc/rabbitmq/
RUN chown -R 1001:1001 /opt/bitnami/
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OpenStack with Cinder storage

**Comment by randradas** [comment]
Hello @moule3053 it looks like the template needs to be filled properly to open an issue, do you need help with it? otherwise I think we can close this issue.
