### ISSUE TITLE
Instructions incomplete for loading definitions with docker

### ISSUE THREAD

**Issue by brettnem** [bitnami/bitnami-docker-rabbitmq#182]
Hello,
I'm using the `bitnami/rabbitmq` container with **docker-compose.** 

I see in the README:

> RABBITMQ_LOAD_DEFINITIONS: Whether to load external RabbitMQ definitions. This is incompatible with setting the RabbitMQ password securely. Default: no.

However, it doesn't say how to specify where that definition file should go, or the contents of the definitions. I would expect that the container either expects you to volume-mount a folder with the definitions in a very specific location, or that there is another env with the definitions themselves within the env. 

Can someone shed some light for me? I can find plenty of kubernetes examples, but I'm trying to do this in docker-compose.

**Comment by javsalgar** [comment]
Hi,

I've been checking and this setting is mostly used in the chart, where we mount a rabbitmq configuration file with this

```
load_definitions = /app/load_definition.json
```

In this sense you would need to mount a RabbitMQ configuration file that points to the load definition file path. Did you try mounting your own RabbitMQ configuration file?

**Comment by brettnem** [comment]
No, but if I did that, what would this ENV provide at all?

It's starting to get unnecessarily tricky and I don't think this was the intention. For example, I would need a volume mount or a customized Dockerfile to move that definition file over. I think ideally if I could include the definition in an ENV itself or if there was another ENV to specify the full absolute path of the definitions that would be ideal. This seems to have been written for charts but not at all for docker-compose builds. 

I'm imagining something like: 
```
RABBITMQ_LOAD_DEFINITIONS=yes
RABBITMQ_DEFINITION_PATH=/opt/config/rabbitmq_definitions.json
```

And then I can work my magic to put it where it expects it. 

I'd also be ok if the image *expects* it to be in a certain path so that if you set `RABBITMQ_LOAD_DEFINITIONS` it always looks for a specific absolute file. 

What isn't very manageable is if I have to create my own Dockerfile to get those configs and files into place. It also seems quite messy to have to mount a customized config file just to get this functionality. 

Or am I missing something entirely?? Either way, the documentation isn't clear that this method does not work outside of charts. Thanks for your assistance!

**Comment by javsalgar** [comment]
Hi,

I agree that we should improve the user experience on docker-compose installations. I think that adding the RABBITMQ_DEFINITION_PATH could be useful. As we are open to contributions, would you like to submit a PR with the feature? If not, we will work on it but, as it is not a critical feature, we would not be able to guarantee an ETA.
