### ISSUE TITLE
use Maintenance mode when stopping a node

### ISSUE THREAD

**Issue by felixhuettner** [bitnami/bitnami-docker-rabbitmq#195]
### Name and Version

bitnami/rabbitmq:3.9.13-debian-10-r40

### What is the problem this feature will solve?

When stopping a rabbitmq node it is possible to transfer the primary of quorum queues in a graceful way before the node is shut down. This reduces the load and failover time.

For detailed discussions see the issue at the official rabbitmq operator (https://github.com/rabbitmq/cluster-operator/issues/320)

### What is the feature you are proposing to solve the problem?

use `rabbitmq-upgrade drain` to put a node into maintenance mode before shutdown.

Include this step before `stop_app` in `nodeshutdown.sh`

**Comment by carrodher** [comment]
Thanks for the suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by felixhuettner** [comment]
I'm sorry. I will not be  able to implement this as we are no longer using the bitnami rabbitmq image (so i cant allocate time to it).
