### ISSUE TITLE
RabbitMq initialization fails in a root restricted environment

### ISSUE THREAD

**Issue by scottmf** [bitnami/bitnami-docker-rabbitmq#197]
### Name and Version

bitnami/rabbitmq:3.9.13-debian-10-r38

### What steps will reproduce the bug?

When docker / k8s runtimes restrict the root user a rabbitmq container cannot start up.

To reproduce:

```
$ docker run --user 1001:1001 --name rmq -d -p 5552:5552 -p 5672:5672 -p 15672:15672 -e 'RABBITMQ_USERNAME=guest' -e 'RABBITMQ_PASSWORD=guest' bitnami/rabbitmq:3.9.13-debian-10-r36
7715aea5812e5dfe82b4e92a8c80ee7f94cf3de5ed3720f9fcd0ef61eaecccd1
$ docker logs rmq -f
rabbitmq 01:45:59.99
rabbitmq 01:45:59.99 Welcome to the Bitnami rabbitmq container
rabbitmq 01:45:59.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 01:45:59.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 01:45:59.99
rabbitmq 01:46:00.00 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 01:46:00.01 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 01:46:00.03 INFO  ==> Initializing RabbitMQ...
/opt/bitnami/scripts/librabbitmq.sh: line 379: /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf: Permission denied
```

### What is the expected behavior?

The RabbitMQ container should start successfully in an environment where the root user is restricted

### What do you see instead?

container does not start

**Comment by rafariossaa** [comment]
Hi, 
  The [docker image is run with user 1001](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/c9c7a9008584137bb79fd73adc7e689a4cec99ba/3.9/debian-10/Dockerfile#L35), but as the files are in root owned folder, you can not force the user to be in the group  `1001`.  
```
$ docker run --user 1001 --name rmq -d -p 5552:5552 -p 5672:5672 -p 15672:15672 -e 'RABBITMQ_USERNAME=guest' -e 'RABBITMQ_PASSWORD=guest' bitnami/rabbitmq:3.9.13-debian-10-r36

or (that is de same as above as USER 1001 is included in the Dockerfile)

$ docker run  --name rmq -d -p 5552:5552 -p 5672:5672 -p 15672:15672 -e 'RABBITMQ_USERNAME=guest' -e 'RABBITMQ_PASSWORD=guest' bitnami/rabbitmq:3.9.13-debian-10-r36
```

**Comment by scottmf** [comment]
Due to our compliance & security standards we cannot run our containers as the root user.  I cannot use this imagine in our environment.  I appreciate the workaround you are suggesting but it will not work for us :(

**Comment by rafariossaa** [comment]
@scottmf , the reason behind this is built this way is because we need to support the execution using a random users. This is needed to support Openshift out of the box.

@MXSH-Dev thanks for providing this info.

**Comment by MXSH-Dev** [comment]
Hi @rafariossaa can you please elaborate on what you meant by `This is needed to support Openshift out of the box.`? We are deploying the bitnami version of rabbit mq in an Open Shift environment. And I had to do the trick I mentioned above to get it working. The reason is that Open Shift does not like the default user 1001, I had to change it to a specific Openshift project user id to make it work.

**Comment by rafariossaa** [comment]
Hi,
 @MXSH-Dev, The idea is that you don't need to make changes in this image to be run in openshift due to [openshift assigning](https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids) a random user ID to the namespace.

  @scottmf, not sure if [this info](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/) would help.

**Comment by scottmf** [comment]
@rafariossaa , the information you pointed to is what we use in our k8s clusters.  My understanding, and what i have seen during my experimentation, is that the security context you pointed out is the same as running the docker command that fails above with `--user 1001:1001`. Since it is bootstrapping the container with user 1001 I don't see how it helps this situation

**Comment by rafariossaa** [comment]
Hi,
  There is not problem in changing the user, as the user belong to group root it will be able to reach them. As there is not root user in the container it would be impossible for the user to change the files or directories.
