### ISSUE TITLE
start failed after once

### ISSUE THREAD

**Issue by xiaopihai1** [bitnami/bitnami-docker-rabbitmq#198]
### Name and Version

docker.io/bitnami/rabbitmq:3.9

### What steps will reproduce the bug?

Hello, when I first started, the container started successfully. When docker-compose went down, it was found that the docker-compose container could not be started because the mounted volume already existed. Therefore, after I deleted the existing volume, the container could be started normally. Volum is mounted on a highly efficient cloud disk and I'm not sure what I can do to fix that. Can you give me some help? Thank you very much

### What do you see instead?

Couldn't cluster with node 'rabbit@stats'.

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate the commands you have run and the errors you got ?.
