### ISSUE TITLE
add a plugin bitnami/rabbitmq:3.9.8 .

### ISSUE THREAD

**Issue by doublewaters** [bitnami/bitnami-docker-rabbitmq#201]
### Name and Version

rebbitmq:3.9.8

### What steps will reproduce the bug?

I insatlled a rebbitmq in k8s via helm ,now I want to add a plugin(rabbitmq_delayed_message_exchange) in `/opt/bitnami/rabbitmq/plugins` , I build a new docker image from bitnami/rabbitmq:3.9.8 .
this is my Dockerfile:
```
FROM  bitnami/rabbitmq:3.9.8
COPY rabbitmq_delayed_message_exchange-3.9.0.ez /opt/bitnami/rabbitmq/plugins
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
```
and i set new image ,and it logs 
![image](https://user-images.githubusercontent.com/35893428/163324155-7fffef7d-c227-439e-96f9-864af5a105a6.png)
it only load a plugin when starting ,and  the plugin rabbitmq_management(it should be enabled by default) that doesn't start

this log from The original images
![image](https://user-images.githubusercontent.com/35893428/163324833-68c437d5-6a72-443c-b100-25317770d20b.png)

### What do you see instead?

I want to load my plugin and default plugin can start together when pod starting

**Comment by carrodher** [comment]
The image support some environment variables to add plugins:
- `RABBITMQ_PLUGINS`: Comma, semi-colon or space separated list of plugins to enable during the initialization. No defaults.
- `RABBITMQ_COMMUNITY_PLUGINS`: Comma, semi-colon or space separated list of URLs where to download custom plugins during the initialization. No defaults.

Can you try using them?

**Comment by doublewaters** [comment]
I think i can set environment variables in helm chart,tanks for you suggestion 🙇‍
