### ISSUE TITLE
Create a symbolic link on the Volume

### ISSUE THREAD

**Issue by vhuezo** [bitnami/bitnami-docker-rabbitmq#203]
### Name and Version

bitnami/rabbitmq:latest

### What steps will reproduce the bug?

`--mount type=volume,src=rabbitmq-bitnami,dst=/bitnami/rabbitmq/ `

`docker run  -v rabbitmq-bitnami2:/bitnami/rabbitmq/ bitnami/rabbitmq:latest`

### What do you see instead?

I create the Volume and it does not store the data, Create a symbolic link

### Additional information

I create the Volume and it does not store the data, Create a symbolic link

**Comment by migruiz4** [comment]
Hi @vhuezo,

The volume path for RabbitMQ persistence to work has to be `/bitnami/rabbitmq/mnesia`, not `/bitnami/rabbitmq/`.

```
docker run -v rabbitmq-bitnami:/bitnami/rabbitmq/mnesia bitnami/rabbitmq:latest
```
