### ISSUE TITLE
Segmentation fault /opt/bitnami/scripts/libos.sh: line 336

### ISSUE THREAD

**Issue by kylehqcom** [bitnami/bitnami-docker-rabbitmq#205]
### Name and Version

bitnami/rabbitmq:latest

### What steps will reproduce the bug?

Running docker-compose up/build on Apple M1 chipset using the latest + bitnami/rabbitmq:3.8 + bitnami/rabbitmq:3.9 images and getting a segmentation fault so the service cannot run in the background.

Error refers to line https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh#L336

The debug setting of true or false creates the segmentation fault.

rabbitmq 02:26:18.73 INFO  ==> Starting RabbitMQ in background...
feed-army-rabbitmq  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
feed-army-rabbitmq  | /opt/bitnami/scripts/libos.sh: line 336:   112 Segmentation fault      "$@"
feed-army-rabbitmq  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### What is the expected behavior?

No segmentation fault and the process/service starts as required. 

### What do you see instead?

Docker logs output on run

<img width="703" alt="Screenshot 2022-06-04 at 7 40 51 PM" src="https://user-images.githubusercontent.com/424321/172032716-a2c02f18-5b59-4e40-aaf7-7498d66052ba.png">

Docker compose settings (with password removed)
<img width="1004" alt="Screenshot 2022-06-04 at 7 41 26 PM" src="https://user-images.githubusercontent.com/424321/172032732-b145bd2d-6983-41f0-85b3-a53ada8de0d4.png">

### Additional information

Issue on image latest, bitnami/rabbitmq:3.8 & bitnami/rabbitmq:3.9

**Comment by kylehqcom** [comment]
Addendum if at all helpful, the official https://hub.docker.com/_/rabbitmq image runs with error - the issue it would seem is bound only to the debug output code block. 

https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh#L327-L342

**Comment by javsalgar** [comment]
Hi,

Currently we don't have support for ARM-based chips. It is being under discussion but there are no short-term plans on releasing arm containers.

**Comment by kylehqcom** [comment]
Ok thanks, I wasn't aware of this. I will use the official RabbitMQ image from here to continue. Again thanks.
