### ISSUE TITLE
RabbitMQ container fails to launch due to EEXIST

### ISSUE THREAD

**Issue by localghost** [bitnami/bitnami-docker-rabbitmq#49]
**Description**
`bitnami/rabbitmq` container fails to launch.

**Steps to reproduce the issue:**
1. Run the container: `docker run -it --rm bitnami/rabbitmq`

**Describe the results you received:**
I get following error:
```
nami    INFO  Initializing rabbitmq
rabbitm INFO  Creating RabbitMQ System User...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/rabbitmq/bin' -> '/opt/bitnami/rabbitmq/sbin'
```

**Describe the results you expected:**
Container starts successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Looks to be connected to #30 (but for me it happens all the time).

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: l82so4ji9d7j60av34ww0duig
 Is Manager: true
 ClusterID: v6kooegsjuheilvd2q9u40d56
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.9.4.51
 Manager Addresses:
  10.9.4.51:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.797 GiB
Name: localhost.localdomain
ID: K4LW:ZLG5:4NJB:5HT3:YRPL:FRNS:BTEW:LT2S:RBID:MJDY:SI3A:YEDF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 docker-registry:5000
 127.0.0.0/8
Registry Mirrors:
 http://docker-registry:5001
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):
N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
CentOS 7.2 on KVM

**Comment by davidbhlm-github** [comment]
Hi @localghost ,

I believe this is a because your docker host is using overlayfs as the storage backend for docker. We have seen similar issues with Redhat/CentOS hosts before and we recommend switching to a more stable storage driver. See [bitnami/bitnami-docker-testlink#17](https://github.com/bitnami/bitnami-docker-testlink/issues/17) for a sample test command.

RHEL treats OverlayFS as a preview filesystem. The following document https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html lists the problems and possible workarounds for using OverlayFS with Docker on RHEL 7.2.

Please let us know if it works for you.

**Comment by localghost** [comment]
Hi,

Thanks for the hint, switching to devicemapper fixed the issue.
