### ISSUE TITLE
Can we expose vm_memory_high_watermark?

### ISSUE THREAD

**Issue by listingmirror** [bitnami/bitnami-docker-rabbitmq#52]
This sees the memory of the entire machine, and uses 40% of it. That is wrong.

It should be configurable, and default to requests.memory I think

**Comment by chipironcin** [comment]
Hi @listingmirror 
The value is 40% by default as a conservative value because in the worst case it can take up to 80% of the RAM.

From RabbitMQ documentation:
>The default memory threshold is set to 40% of installed RAM. Note that this does not prevent the RabbitMQ server from using more than 40%, it is merely the point at which publishers are throttled. Erlang's garbage collector can, in the worst case, cause double the amount of memory to be used (by default, 80% of RAM). It is strongly recommended that OS swap or page files are enabled.

If you still want to modify that value you can execute the following command and your modified configuration will be persisted:
```
docker exec <your_container_id> rabbitmqctl set_vm_memory_high_watermark <fraction>
# Example
docker exec 37a83df20e rabbitmqctl set_vm_memory_high_watermark 0.4
```

**Comment by listingmirror** [comment]
Hi @chipironcin 

Here is that problem. It defaults to 40% of NODE ram not POD ram.

Say I have a node with 30GB ram. But I make a pod with a request of 4 GB of ram, and a limit of 5 GB of ram.

Your image will set the highwater mark to 30 * .4 = 12 GB. This is way past the limit.. as soon as you hit 5 GB the image will be killed by kube and rebooted.

I see three reasonable fixes for this...

1) Provide a hook for us to manually specify the highwater mark. I know my pod has a limit of 4 GB, so I can manually set the highwater mark to 1.6 GB

2) Inspect the available POD memory at the request / limit level, and use that to set this value

3) Provider a hook somewhere for rabbitmqctl commands to fire after container launch. Since in this case we can set the highwater mark post container startup, we could just fire off a series of commands to adjust things like this.

**Comment by chipironcin** [comment]
>Your image will set the highwater mark to 30 * .4 = 12 GB
It is not the image, but RabbitMQ with its default configuration.

It seems RabbitMQ is detecting the total amount of RAM wrongly, please read this issue:
https://github.com/rabbitmq/rabbitmq-server/issues/205

If you want to modify this setting manually to cover your issue you can use the following commands:
```
# docker exec or kubectl exec
docker exec <your_container_id> rabbitmqctl set_vm_memory_high_watermark <fraction>
docker exec <your_container_id> rabbitmqctl set_vm_memory_high_watermark absolute <value>
# Example
docker exec 37a83df20e rabbitmqctl set_vm_memory_high_watermark 0.4
docker exec 37a83df20e rabbitmqctl set_vm_memory_high_watermark absolute 1.6G
```

**Comment by listingmirror** [comment]
@chipironcin I know how to set it manually. That doesn't work in kubernetes. At any point in time my image can be killed and respawned on a new server. (Most likely due to things like a server is dying or I am upgrading my cluster). When that happens, any handset properties die.

Hence, my request that there is an easier way to set this value in the image itself. That way it will work across pod reschedules.

If you ever have to go hand tweak an image to "make it work", you are missing the point of docker and doing it wrong. The settings need baked into the image / config.

**Comment by chipironcin** [comment]
You are right, if your pod get respawned that property won't persist if manually set.

We cannot add as much options to the image as properties exists for RabbitMQ.
In order to provide your own entire settings file and override the inbuilt one you can follow the steps in the README (https://github.com/bitnami/bitnami-docker-rabbitmq#configuration-file).
