### ISSUE TITLE
[RFE] Use rabbitmq-autocluster to create the clusters 

### ISSUE THREAD

**Issue by Gsantomaggio** [bitnami/bitnami-docker-rabbitmq#53]
Hi,
You should consider to use [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster) plugin to create the clusters.  

The current  version is [`0.8.0`](https://github.com/rabbitmq/rabbitmq-autocluster/releases/tag/0.8.0)

`RABBITMQ_CLUSTER_NODE_NAME` needs a node to bind the other nodes, with rabbitmq-autocluster you can use different backends and bind the nodes dynamically.

Currently it supports:

- AWS EC2 tags
- AWS Autoscaling Groups
- Kubernetes
- DNS A records
- Consul
- etcd

There are a couple of examples to use it on Kubernetes:

- [Deploy on K8s](https://github.com/rabbitmq/rabbitmq-autocluster/tree/master/examples/k8s_minikube)

- [Deploy on K8s using StatefulSet Controller](https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable/examples/k8s_statefulsets) 

The full documentation is available [here](https://github.com/rabbitmq/rabbitmq-autocluster#rabbitmq-autocluster)

**Comment by prydonius** [comment]
@Gsantomaggio this looks awesome, and definitely something we should try and enable (especially for the chart).

cc @sameersbn

**Comment by jotadrilo** [comment]
@prydonius it seems RabbitMQ 3.7.0 will include that functionality in its core.
See [this](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0-rc.1) release candidate.

**Comment by Gsantomaggio** [comment]
Yes it will.
I was thinking about 3.6.x !


Btw you have to change the way how you bind the nodes, even with the new version!

**Comment by prydonius** [comment]
If this is going to be included in core in 3.7.0, it seems like it might be worth waiting until then.

**Comment by Gsantomaggio** [comment]
Ok, so I can close this PR.
