### ISSUE TITLE
ENV VARS for SSL cert file

### ISSUE THREAD

**Issue by alseddnm** [bitnami/bitnami-docker-rabbitmq#58]
**Description**

Hey guys  we don't see a parameter for *RABBITMQ_SSL_CERTFILE*. I am trying to establish SSL connection to rabbitmq in kubernetes cluster using github.com/kubernetes/charts/tree/master/stable/rabbitmq
Now I start looking into how to enable SSL for rabbitmq helm chart, however I don't see any env vars parameter listed in the docker file for rabbitmq bitnami/rabbitmq image?
**Steps to reproduce the issue:**
My service has been deployed in kubs cluster and is publishing a message to rabbitmq which is deployed in the same cluster.
**Describe the results you received:**
I got this error in the log _javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection_

I assumed the error above because I was trying to connect over ssl from the client and the server (rabbitmq helm chart) does not have SSL enabled.

**Comment by alseddnm** [comment]
Is the bitnami-docker-rabbitmq supports ssl?

**Comment by alseddnm** [comment]
@tompizmor @sameersbn  @bitnami-bot ?

**Comment by chipironcin** [comment]
Hello @alseddnm 
The bitnami-docker-rabbitmq container is not ready yet to deal with SSL connections.
I will move this to the right team to see if we can easily adapt the current container to support it.

Will post updates in this thread. Thanks

**Comment by johnarnold** [comment]
Update?

**Comment by johnarnold** [comment]
@chipironcin  Any update?

**Comment by javsalgar** [comment]
As far as I know, SSL is still not enabled in our container. However, in a Kubernetes environment, the SSL configuration makes sense to be set using Ingress. According to https://github.com/kubernetes/kubernetes/issues/23291#issuecomment-392994068, this is something that ingress could potentially handle.
