### ISSUE TITLE
Cannot login to Management UI

### ISSUE THREAD

**Issue by fikri5758** [bitnami/bitnami-docker-rabbitmq#66]
**Description**
`version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
  rabbitmq_data:
    driver: local`

I use that docker-compose, but i can't login...

**Comment by juan131** [comment]
Duplicate: https://github.com/bitnami/bitnami-docker-rabbitmq/issues/65
