### ISSUE TITLE
RabbitMQ with high performance erlang

### ISSUE THREAD

**Issue by thewire247** [bitnami/bitnami-docker-rabbitmq#67]
Hi.

Could I request that high performance erlang (HiPE) is added to the rabbitmq images as an option to use. It can improve performance on high performance clusters by up to 50%.

https://www.cloudamqp.com/blog/2014-03-31-rabbitmq-hipe.html
http://www.rabbitmq.com/configure.html#config-items

Thanks

**Comment by juan131** [comment]
Sure! I think we can add this option and it seems very interesting for production environments
@javsalgar @tompizmor what do you think?

**Comment by michaelklishin** [comment]
HiPE is gone in modern Erlang releases and [replaced with a JIT](https://blog.rabbitmq.com/posts/2021/03/erlang-24-support-roadmap/). This should be closed.

**Comment by alemorcuq** [comment]
Thanks for the information, @michaelklishin ! Actually it looks like HiPE support was dropped in Erlang 22:

```
hipe_compile | Do not use. This option is no longer supported. HiPE supported has been dropped starting with Erlang 22.
```

https://www.rabbitmq.com/configure.html#config-items
