### ISSUE TITLE
FEATURE REQUEST: support rmq-hashed passwords

### ISSUE THREAD

**Issue by anapsix** [bitnami/bitnami-docker-rabbitmq#74]
RabbitMQ supports `sha256 / sha512` hashed password, according to [documentation](https://www.rabbitmq.com/passwords.html).
Instead of passing password in clear text to the container (or k8s pod/secret spec) , It would be great to be able to use hashed password.

**Comment by juan131** [comment]
Thanks for opening this issue @anapsix ! I agree, it's a feature we should be using. I'll open a task to support it and add it on future releases of this Docker image.

We'll keep you updated.

**Comment by anapsix** [comment]
So far, I could not find a was to get hashed password into RabbitMQ though anything but API..
so.. possible implementation, I was thinking about:
1. create user with randomly generated password on start
2. use credentials to hit RabbitMQ API endpoint to change the password passing HASH 
3. profit

But I'm having hard time understanding where NAMI get's all the settings for `rabbitmq` module, what it supports, etc.. and if there is a way of adding a post-start task to it..

**Comment by juan131** [comment]
Hi @anapsix 

> But I'm having hard time understanding where NAMI get's all the settings for rabbitmq module, what it supports, etc..

Nami gets a serie of parameters based on env. variables (see [rabbitmq-inputs.json](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.7/rootfs/rabbitmq-inputs.json)). Then, it uses them to configure RabbitMQ. The configuration file which is generated can be found at **/opt/bitnami/etc/rabbitmq/rabbitmq.config**.

All the env. variables that can be set are documented on the [configuration](https://github.com/bitnami/bitnami-docker-rabbitmq#configuration) section.

> . and if there is a way of adding a post-start task to it..

You can add you custom scripts on the [app-entrypoint.sh](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.7/rootfs/app-entrypoint.sh).

**Comment by juan131** [comment]
HI @anapsix 

Thanks so much for the contribution. I'm taking a look.

**Comment by anapsix** [comment]
See my work on this feature in NAMI in https://github.com/bitnami/bitnami-docker-rabbitmq/pull/75#issuecomment-400809462

**Comment by juan131** [comment]
Hi @anapsix 

Great thanks!

**Comment by juan131** [comment]
Hi @anapsix 

I'm glad to announce that we just released a new revision (**3.7.7-r35**) of this Docker Image and it supports hashed passwords.

Please check the Notable changes section below:
https://github.com/bitnami/bitnami-docker-rabbitmq#377-r35

We also updated the [Configuration](https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables) section of the README.md file with more info about this env. variable.

Please feel free to use it and provide us feedback!

**Comment by anapsix** [comment]
coolio, thx!
