### ISSUE TITLE
image runs as root

### ISSUE THREAD

**Issue by itaied246** [bitnami/bitnami-docker-rabbitmq#76]
I've tried deploying the image to `openshift`, but it says that the image runs as `root` user.

`openshift` doesn't allow for images to run as root,
and it also requires arbitrary user execution.

Are there any plans to run the image as non-root user?

**Comment by marcosbc** [comment]
Hi @itaied246,

We're already working on changing our RabbitMQ container so it runs as a non-root user. We expect to have it released by end of week.

We'll let you know once released.

**Comment by javsalgar** [comment]
Hi,
We just released a non-root version of the container. If you find any issues, please let us know :)
