### ISSUE TITLE
Cannot login to management panel

### ISSUE THREAD

**Issue by dasjestyr** [bitnami/bitnami-docker-rabbitmq#84]
**Description**

After running a new container using the `bitnami/rabbitmq:latest` image. The default login of user/bitnami does not work. I get a "login failed" message and in the browser console, I can see a 401 error.

**Steps to reproduce the issue:**

As instructed in the docker hub repo, run the following
``` sh
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-rabbitmq/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

Browse to http://localhost:15672 and attempt to login with username: user and password: bitnami

**Describe the results you received:**

Login failed.

**Describe the results you expected:**
Login is successful and the management panel is displayed

**Additional information you deem important (e.g. issue happens only occasionally):**

I've also tried explicitly setting the username and password via the environment variables on startup.

**Version**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Ubuntu 18.04.1 running on Windows 10 1803 Hyper-V enhanced mode

**Comment by javsalgar** [comment]
Hi,

I am unable to reproduce the issue. I was able to enter the login page without issues.

![image](https://user-images.githubusercontent.com/1133777/50037483-fcf6fd80-0011-11e9-8da6-60918954d524.png)


Could you check if there are no volumes attached?

```
docker-compose down -v
```

**Comment by loxybjorn** [comment]
Can you try logging in using "user"/"guest" instead of "user"/"bitnami"? I've set up a container where the default login was that for some reason.

**Comment by dasjestyr** [comment]
Sorry for the delay, I am away from that computer but I wanted to let you
know I didn't abandon this. I will test this as soon as I get back!

**Comment by javsalgar** [comment]
Let us know if you still have issues ;)

**Comment by dasjestyr** [comment]
I'm not actually sure what changed on my side, but I just tried the same thing on a different box and everything was perfectly fine. Mystery. Thanks for the help.
