### ISSUE TITLE
how to use  multiple machines create rabbitmq-clusters?

### ISSUE THREAD

**Issue by Michael728** [bitnami/bitnami-docker-rabbitmq#90]
It's a very usefule project for me.I have a proble, I use the `docker-compose-cluster.yml` file in the project on one host, but how can I create rabbitmq cluster use multiple machines?

**Comment by juan131** [comment]
Hi @Michael728 

Do you have access to a Kubernetes environment? The easiest way to deploy efficiently a RabbitMQ cluster with several nodes is using the RabbitMQ Helm chart. In the link below you can find it:

https://github.com/helm/charts/tree/master/stable/rabbitmq

That chart will allow you to easily scale horizontally your RabbitMQ chart.

**Comment by Michael728** [comment]
@juan131 no, I have not Kubernetes environment， I still have no idea to use muliple machines create rabbitmq clusters

**Comment by juan131** [comment]
Did you try using the docker-compose below?

https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/docker-compose-cluster.yml

It'll allow you setup a RabbitMQ cluster with 3 nodes.
