### ISSUE TITLE
container can not be restart

### ISSUE THREAD

**Issue by wanghanmin** [bitnami/bitnami-docker-rabbitmq#93]
If use docker-compose to up and stop one instance,when start it again , we get:
/librabbitmq.sh: line 181: /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie: Permission denied

in the script librabbitmq.sh:
chmod 400 "${RABBITMQ_HOME_DIR}/.erlang.cookie" "${RABBITMQ_LIB_DIR}/.erlang.cookie"
so it make the file can not recreate.

**Comment by alemorcuq** [comment]
Hi, @wanghanmin.

I've been able to reproduce your issue. Right now I can think of two possible solutions:

- Give the `.erlang.cookie` file write permissions, i.e., `chmod 600 ...`.
- Only create the `.erlang.cookie` file if it's not already present.

We will fix it as soon as possible. Thank you for reporting it.

Regards,
Alejandro

**Comment by andyhite** [comment]
I've been having this problem for about a week, but have been able to work around it by stopping the container, removing it, then creating / starting it again with `up`.

**Comment by alemorcuq** [comment]
We just released two new images that should fix the issue:

- `3.7.16-debian-9-r3`
- `3.7.16-ol-7-r4`

Thanks again for reporting this issue. Please, don't hesitate to open a new ticket if you find any other problems.

Regards,
Alejandro

cc @wanghanmin @andyhite

**Comment by ssi-anik** [comment]
I am getting this error

![image](https://user-images.githubusercontent.com/2676602/62156118-2f006a00-b32c-11e9-94e9-e7209aaf60ef.png)

**Comment by ssi-anik** [comment]
solution: https://techoverflow.net/2018/12/15/solving-bitnami-docker-redmine-cannot-create-directory-bitnami-mariadb-permission-denied/

**Comment by alemorcuq** [comment]
Hi, @ssi-anik.

Yes, when mounting host directories you have to be careful with the permissions. It should also work if you just set the owner group to root:

```
$ chown -R youruser:root <directory>
```

Regards,
Alejandro
