### ISSUE TITLE
I started this way.

### ISSUE THREAD

**Issue by szbjb** [bitnami/bitnami-docker-rabbitmq#99]
helm install  --name my-release stable/rabbitmq   --set  "persistence.storageClass=gluster-heketi,rabbitmq.username=username,rabbitmq.password=password,service.type=NodePort"

**Comment by rafariossaa** [comment]
Hi @szbjb ,
  Could you provide more info on the issue you are having? 

Thanks forehand

**Comment by szbjb** [comment]
稍等,你看得懂中文吗？
我的持久化存储是这样的Heketi+GlusterFS
persistence.storageClass: "gluster-heketi"


我是通过helm install直接这样安装的
=========================================
helm install  --name my-release stable/rabbitmq   --set  "persistence.storageClass=gluster-heketi,rabbitmq.username=username,rabbitmq.password=password,service.type=NodePort"


===========================================




pod 起来后 我看pod的日志报这个错,然后pod一直再重启
[root@k8s-master ~]# kubectl  logs -f my-release-rabbitmq-575cfd575f-qncch Welcome to the Bitnami rabbitmq container Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues Send us your feedback at containers@bitnami.com nami    INFO  Initializing rabbitmq rabbitm INFO  Creating RabbitMQ System User... rabbitm INFO  Setting RabbitMQ environment... rabbitm INFO  Setting Erlang cookie... rabbitm INFO  Managing RabbitMQ plugins... rabbitm INFO  Configuring RabbitMQ permissions... Error executing 'postInstallation': Group '40001' not found
------------------ 原始邮件 ------------------
发件人: "Rafael Ríos Saavedra"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 晚上11:19
收件人: "bitnami/bitnami-docker-rabbitmq"<bitnami-docker-rabbitmq@noreply.github.com>;
抄送: "东方寻磊"<846492120@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [bitnami/bitnami-docker-rabbitmq] I started this way. (#99)




Hi @szbjb ,
 Could you provide more info on the issue you are having?
 
Thanks forehand

**Comment by szbjb** [comment]
------------------ 原始邮件------------------
发件人:   "Rafael Ríos Saavedra"<notifications@github.com>;
发送时间:   2019年9月10日(星期二)晚上11:19
收件人:   "bitnami/bitnami-docker-rabbitmq"<bitnami-docker-rabbitmq@noreply.github.com>;
抄送:   "东方寻磊"<846492120@qq.com>;"Mention"<mention@noreply.github.com>;
主题:   Re: [bitnami/bitnami-docker-rabbitmq] I started this way. (#99)




Hi @szbjb , 
 Could you provide more info on the issue you are having?
 
Thanks forehand

**Comment by rafariossaa** [comment]
Hi @szbjb ,
  Sorry,  I don't understand chineese. 
  I think this is now solved in: #98 

  If you have any other error don't hesitate to create a new issue.
